---
apiVersion: v1
kind: Service
metadata:
  name: boxcmd
  namespace: boxcmd
spec:
  type: ClusterIP
  selector:
    app: boxcmd
    version: v1.0
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
