// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gcommand

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RemoteCommandClient is the client API for RemoteCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteCommandClient interface {
	ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ReturnMsg, error)
}

type remoteCommandClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteCommandClient(cc grpc.ClientConnInterface) RemoteCommandClient {
	return &remoteCommandClient{cc}
}

var remoteCommandExecCommandStreamDesc = &grpc.StreamDesc{
	StreamName: "ExecCommand",
}

func (c *remoteCommandClient) ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ReturnMsg, error) {
	out := new(ReturnMsg)
	err := c.cc.Invoke(ctx, "/gcommand.RemoteCommand/ExecCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteCommandService is the service API for RemoteCommand service.
// Fields should be assigned to their respective handler implementations only before
// RegisterRemoteCommandService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type RemoteCommandService struct {
	ExecCommand func(context.Context, *Command) (*ReturnMsg, error)
}

func (s *RemoteCommandService) execCommand(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/gcommand.RemoteCommand/ExecCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.ExecCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterRemoteCommandService registers a service implementation with a gRPC server.
func RegisterRemoteCommandService(s grpc.ServiceRegistrar, srv *RemoteCommandService) {
	srvCopy := *srv
	if srvCopy.ExecCommand == nil {
		srvCopy.ExecCommand = func(context.Context, *Command) (*ReturnMsg, error) {
			return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "gcommand.RemoteCommand",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "ExecCommand",
				Handler:    srvCopy.execCommand,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "gcommand.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewRemoteCommandService creates a new RemoteCommandService containing the
// implemented methods of the RemoteCommand service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewRemoteCommandService(s interface{}) *RemoteCommandService {
	ns := &RemoteCommandService{}
	if h, ok := s.(interface {
		ExecCommand(context.Context, *Command) (*ReturnMsg, error)
	}); ok {
		ns.ExecCommand = h.ExecCommand
	}
	return ns
}

// UnstableRemoteCommandService is the service API for RemoteCommand service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableRemoteCommandService interface {
	ExecCommand(context.Context, *Command) (*ReturnMsg, error)
}
