// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: gcommand.proto

package gcommand

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxname string `protobuf:"bytes,1,opt,name=boxname,proto3" json:"boxname,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Params  string `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_gcommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_gcommand_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetBoxname() string {
	if x != nil {
		return x.Boxname
	}
	return ""
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type ReturnMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnMsg string `protobuf:"bytes,1,opt,name=returnMsg,proto3" json:"returnMsg,omitempty"`
}

func (x *ReturnMsg) Reset() {
	*x = ReturnMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnMsg) ProtoMessage() {}

func (x *ReturnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gcommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnMsg.ProtoReflect.Descriptor instead.
func (*ReturnMsg) Descriptor() ([]byte, []int) {
	return file_gcommand_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnMsg) GetReturnMsg() string {
	if x != nil {
		return x.ReturnMsg
	}
	return ""
}

var File_gcommand_proto protoreflect.FileDescriptor

var file_gcommand_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x55, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x78, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x29, 0x0a, 0x09, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x32, 0x48, 0x0a, 0x0d,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x37, 0x0a,
	0x0b, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x67,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a,
	0x13, 0x2e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6e, 0x61, 0x6c, 0x64, 0x6f, 0x61, 0x66, 0x6f, 0x6e,
	0x73, 0x6f, 0x2f, 0x62, 0x6f, 0x78, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gcommand_proto_rawDescOnce sync.Once
	file_gcommand_proto_rawDescData = file_gcommand_proto_rawDesc
)

func file_gcommand_proto_rawDescGZIP() []byte {
	file_gcommand_proto_rawDescOnce.Do(func() {
		file_gcommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_gcommand_proto_rawDescData)
	})
	return file_gcommand_proto_rawDescData
}

var file_gcommand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gcommand_proto_goTypes = []interface{}{
	(*Command)(nil),   // 0: gcommand.Command
	(*ReturnMsg)(nil), // 1: gcommand.ReturnMsg
}
var file_gcommand_proto_depIdxs = []int32{
	0, // 0: gcommand.RemoteCommand.ExecCommand:input_type -> gcommand.Command
	1, // 1: gcommand.RemoteCommand.ExecCommand:output_type -> gcommand.ReturnMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommand_proto_init() }
func file_gcommand_proto_init() {
	if File_gcommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gcommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gcommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcommand_proto_goTypes,
		DependencyIndexes: file_gcommand_proto_depIdxs,
		MessageInfos:      file_gcommand_proto_msgTypes,
	}.Build()
	File_gcommand_proto = out.File
	file_gcommand_proto_rawDesc = nil
	file_gcommand_proto_goTypes = nil
	file_gcommand_proto_depIdxs = nil
}
